blank_issues_enabled: false
contact_links:
    - name: â‰ï¸ Support Question
      url: https://our.umbraco.com
      about: This issue tracker is NOT meant for support questions. If you have a question, please join us on the forum.
    - name: ğŸ“– Documentation Issue
      url: https://github.com/umbraco/UmbracoDocs/issues
      about: Documentation issues should be reported on the Umbraco documentation repository.
    - name: ğŸ” Security Issue
      url: https://umbraco.com/about-us/trust-center/security-and-umbraco/how-to-report-a-vulnerability-in-umbraco/
      about: Discovered a Security Issue in Umbraco?
